[package]
name = "backend"
version = "0.1.0"
description = "Terry Brutus work portfolio backend"

[build]
outputDir = "src/backend/dist"
args = ["--release"]

[canisters.backend]
main = "src/backend/main.mo"

[dependencies]
base = "0.16.0"

[toolchain]
moc = "0.16.3"

[moc]
args = ["--default-persistent-actors", "--actor-idl=src/backend/system-idl", "-no-check-ir"]
